import { MODULE_LIST } from "@tb-frontend/shared/globles";



export const M_App = {
    loader: false,
    topModulesLoader: false,
    flashNewsLoader: false,
    allSimilarAppsLoader: false,
    recentlyAddedLoader: false,
    appStatusloader: false,
    healthFacility: {},
    appTranslations: {
        "APP_TITLE": "Ni-kshay SETU",
        "APP_SUBTITLE": "Support to End TUberculosis",
        "PLACEHOLDER_MOBILE_NUMBER": "Mobile Number",
        "PLACEHOLDER_PASSWORD": "Password",
        "REQUIRED": "Required",
        "EMPTY_PASSWORD": "Required",
        "BTN_LOGIN": "Login",
        "BTN_CREATE_AN_ACCOUNT": "Create an account",
        "LINK_FORGOT_PASSWORD": "Forgot Password",
        "PLACEHOLDER_FULL_NAME": "Full Name",
        "EMPTY_FULL_NAME": "Required",
        "VALIDATION_MOBILE_NUMBER": "Mobile Number must be at least 10 digit",
        "VALIDATION_PASSWORD": "Password must be at least 6 character",
        "VALIDATION_FULL_NAME": "Name must be at list 3 char",
        "VALIDATION_PASSWORD_MATCH": "Password must have at least 1 Lowercase, 1 Uppercase, 1 Numeric and 1 Special character.",
        "DROPDOWN_SELECT_CADRE_TYPE": "Select Cadre Type",
        "UNSELECTED_DROPDOWN_CADRE_TYPE": "Required",
        "DROPDOWN_SELECT_CADRE": "Select Cadre",
        "UNSELECTED_DROPDOWN_CADRE": "Please Select Any",
        "DROPDOWN_SELECT_STATE": "Select State",
        "UNSELECTED_DROPDOWN_STATE": "Please Select Any",
        "BTN_CREATE_MY_ACCOUNT": "Create my account",
        "TEXT_CREATE_AN_ACCOUNT": "I already have an account",
        "LINK_BACK_TO_LOGIN": "Back to login",
        "DROPDOWN_SELECT_DISTRICT": "Select District",
        "UNSELECTED_DROPDOWN_DISTRICT": "Please Select Any",
        "DROPDOWN_SELECT_TU": "Select TU",
        "UNSELECTED_DROPDOWN_TU": "Please Select Any",
        "DROPDOWN_SELECT_HEALTHFACILITY": "Select Health-facility",
        "HEADER_CREATE_AN_ACCOUNT": "Create an account",
        "HEADER_HOME": "Ni-kshay Setu",
        "TITLE_GUIDANCE_ON_CASE_FINDINGS": "Learn About Case Findings",
        "TITLE_PATIENT_MANAGEMENT_TOOL": "Patient Management Tool",
        "TAB_KNOWLEDGE_ASSESSMENT": "ASSESS",
        "TITLE_RESOURCE_MATERIALS": "Resource Materials",
        "TITLE_REFERRAL_HEALTH_FACILITY": "Referral - Health Facility",
        "TITLE_SCREENING": "Screening Tool",
        "TITLE_DIAGNOSIS_ALGORITHM": "Diagnostic Care Cascade",
        "TITLE_TREATMENT_ALGORITHM": "Treatment Care Cascade",
        "TITLE_GUIDANCE_ON_ADR": "Guidance on ADR",
        "TITLE_LATENT_TB_INFECTION": "TB Preventive Treatment",
        "TITLE_CASE_DEFINITION": "Case Definition",
        "DRAWER_IIPHG": "Ni-kshay Setu",
        "DRAWER_CASE_DEFINITION": "Case Definition",
        "DRAWER_PATIENT_MANAGEMENT_TOOL": "Patient Management Tool",
        "DRAWER_CGC_INTERVENTION": "NTEP Intervention",
        "DRAWER_KNOWLEDGE_ASSESSMENT": "Knowledge Assessment",
        "DRAWER_RESOURCE_MATERIALS": "Resource Materials",
        "DRAWER_REFERRAL_HEALTH_FACILITY": "Referral - Health Facility",
        "DRAWER_MY_ACCOUNT": "My Account",
        "DRAWER_CONTACT_US": "Contact Us",
        "DRAWER_CHANGE_APPLICATION_LANGUAGE": "Change Application Language",
        "DRAWER_ABOUT_IIPHG": "Partners and Developers",
        "DRAWER_ABOUT_CGC_PROJECT": "About Us",
        "DRAWER_SIGN_OUT": "Sign Out",
        "DRAWER_POWERED_BY": "Powered by",
        "DRAWER_DIGIFLUX_IT_SOLUTIONS": "Digiflux IT Solutions",
        "TAB_HOME": "Home",
        "TAB_GUIDANCE": "LEARN",
        "TAB_PMT": "MANAGE",
        "TAB_ACCOUNT": "Account",
        "TAB_CHAT": "Chat",
        "ACCOUNT_CHANGE_PASSWORD": "Change Password",
        "SUBTITLE_SCREENING": "Screening tool is designed to assess if the presenting symptoms require a person to be tested for Tuberculosis (TB).",
        "SUBTITLE_SCREENING_TWO": "It will take you to some basic questions and will determine the result based on inputs.",
        "TEXT_SCREENING_AGE": "Age (years)",
        "TEXT_SCREENING_WEIGHT": "Weight (kgs)",
        "TEXT_SCREENING_HEIGHT": "Height (cms)",
        "BTN_START": "Start",
        "PLACEHOLDER_SEARCH": "Search",
        "TEXT_FILTERS": "FILTERS",
        "TEXT_CLEAR_ALL": "CLEAR ALL",
        "TEXT_CLOSE": "Close",
        "TEXT_APPLY": "Apply",
        "FILTER_BOTTOM_FILTER": "Filter",
        "FILTER_BOTTOM_SORT": "Sort",
        "FILTER_BOTTOM_SORT_BY": "Sort by",
        "FILTER_BOTTOM_SORT_NAME_AZ": "Name (A - Z)",
        "FILTER_BOTTOM_SORT_NAME_ZA": "Name (Z - A)",
        "CARD_AVAILABLE_FACILITIES": "Available Facilities",
        "CARD_GET_DIRECTION": "Get Direction",
        "CARD_ASSESSEMENT_CURRENT_ASSESSMENTS": "Current Assessments",
        "CARD_ASSESSEMENT_PAST_ASSESSMENTS": "Past Assessments",
        "CARD_RESOURCE_MATERIALS_PDFS": "NTEP Guidelines",
        "CARD_RESOURCE_MATERIALS_VIDEOS": "Videos",
        "CARD_RESOURCE_MATERIALS_PRESENTATIONS": "Presentations",
        "CARD_RESOURCE_MATERIALS_DOCUMENTS": "Documents",
        "CARD_RESOURCE_MATERIALS_OTHERS": "Others",
        "HEADER_SUPPORT": "Support",
        "HEADER_CHAT_TITLE": "Ni-kshay Setu",
        "PLACEHOLDER_CHAT_TYPE_MESSAGE": "Type your message here",
        "SUBTITLE_CONTACT_US": "Transforming the fight towards elimination",
        "VALIDATION_CHARACTER": "minimum 4 Charater",
        "PLACEHOLDER_NAME": "Name",
        "PLACEHOLDER_EMAIL": "Email",
        "PLACEHOLDER_MESSAGE": "Message",
        "PLACEHOLDER_SUBJECT": "Subject",
        "PLACEHOLDER_OLD_PASSWORD": "Old Password",
        "PLACEHOLDER_NEW_PASSWORD": "New Password",
        "PLACEHOLDER_CONFIRM_PASSWORD": "Confirm Password",
        "TITLE_KNOWLEDGEASSESSMENT_ASSIGNMENT_NAME": "Assignment Name",
        "TITLE_KNOWLEDGEASSESSMENT_TIME_TO_COMPLETE": "Time to complete",
        "TITLE_KNOWLEDGEASSESSMENT_NO_OF_QUESTIONS": "No. of questions",
        "TITLE_KNOWLEDGEASSESSMENT_REMAINING_TIME": "Remaining time",
        "TITLE_KNOWLEDGEASSESSMENT_QUESTION": "Question",
        "BTN_C_ASMENT_SAVE": "Save",
        "BTN_C_ASMENT_S_AND_S_ANS": "Save & Show answer",
        "BTN_C_ASMENT_SUBMIT": "Submit",
        "BTN_C_ASMENT_NEXT": "Next",
        "BTN_C_ASMENT_PREVIOUS": "Previous",
        "BTN_C_ASMENT_SKIP": "Skip",
        "TITLE_K_ASMENT_RES_COMPL_ON": "Completed on",
        "TITLE_K_ASMENT_RES_ASIGNMENT_NAME": "Assignment Name",
        "TITLE_K_ASMENT_RES_ATTEMPTED": "Attempted",
        "TITLE_K_ASMENT_RES_SKIPPED": "Skipped",
        "TITLE_K_ASMENT_RES_RIGHT_ANSWERS": "Right Answers",
        "TITLE_K_ASMENT_RES_WRONG_ANSWERS": "Wrong Answers",
        "TITLE_K_ASMENT_RES_SCORE": "SCORE",
        "LINK_K_ASMENT_RES_BACK_TO_HOME": "Back To Home",
        "RESULT": "Result",
        "RESULT_TY": "Thank you for taking the assessment",
        "RESULT_NOTTB_TEXT": "If the information provided by you is accurate, the person does not appear to have significant symptoms of Tuberculosis (TB).",
        "RESULT_TB_TEXT": "If the information provided by you is accurate, it indicates that the person might have",
        "NUTRITION_OUTCOME": "Nutrition Outcome",
        "CURRENT_WEIGHT": "Current Weight",
        "CURRENT_BMI_VALUE": "Current BMI Value",
        "DESIRABLE_WEIGHT": "Desirable Weight",
        "MINIMUM_ACCEPTABLE_WEIGHT": "Minimum acceptable weight",
        "DESIRABLE_WEIGHT_GAIN": "Desirable weight gain",
        "MINIMUM_WEIGHT_GAIN_REQUIRED": "Minimum weight gain required",
        "DESIRABLE_DAILY_CALORIC_INTAKE": "Desirable daily caloric intake",
        "DESIRABLE_DAILY_PROTEIN_INTAKE_RANGE": "Desirable Daily Protein Intake Range",
        "NUTRITION_OUTCOME_DETAILS": "Next Step for Presumptive Case",
        "REFERENCE": "Reference",
        "SYMPTM_QUESTION": "Are you experiencing any of the following symptoms?",
        "OBESE": "Obese",
        "OVERWEIGHT": "Overweight",
        "NORMAL": "Normal",
        "MILD_UNDERWEIGHT": "Mild underweight",
        "MODERATE_UNDERWEIGHT": "Moderate underweight",
        "SEVERE_UNDERWEIGHT": "Severe underweight",
        "EXTREME_UNDERWEIGHT": "Extreme underweight",
        "HEADER_CONTACT_US": "Contact Us",
        "CHAT_QUESTIONSTATICADD_LOAD_MORE": "Load More",
        "CHAT_QUESTIONSTATICADD_BACK_TO_TOPICS": "Back to main topics",
        "CHAT_QUESTIONSTATICADD_MESSAGE": "You can also type any Keyword below.",
        "CHAT_QUESTIONSTATICADD_SORRY": "Sorry! I could not find any relevant information for the above topic. You can choose from most asked topics or contact us.",
        "CHAT_QUESTIONSTATICADD_CONTACT": "Contact Us",
        "BOT_SHORT_NAME": "Ask Setu",
        "CHAT_QUESTIONANSWERTYPE_LOAD_SIM_QUES": "Load similar Questions",
        "CHAT_KEYWORDTYPELIST_MORE": "More",
        "BOT_NAME": "Ni-kshay Setu",
        "HEADER_CHANGE_PASS": "Change Password",
        "BTN_CONTACT_US": "Submit",
        "CARD_RESOURCE_MATERIALS_PDFS_OFFICE_ORDERS": "Office Orders",
        "TITLE_CGC_INTERVENTION": "NTEP Intervention",
        "TITLE_KNOWLEDGE_ASSESSMENT": "Knowledge Assessment",
        "CONTACT_US_SUBJECTS": "Technical,Non-Technical,Other",
        "CHAT_USERSIDE_YOU": "You",
        "TABLE_NAME": "Name",
        "TABLE_SIZE": "Size",
        "TABLE_UPLOAD_DATE": "Upload Date",
        "HEADER_FACILITIES": "Facilities",
        "HEADER_LOCATION": "Location",
        "END_MESSAGE": "Yay! You have seen it all",
        "LOGIN_AGAIN": "Want to try login again?",
        "HEADER_PROFILE_PAGE": "Profile Page",
        "HEADER_PERSONAL_DETAILS": "Personal Details",
        "CADRE_LEVEL": "Cadre Level",
        "HEADER_STATE": "State",
        "HEADER_CONTACT_DETAILS": "Contact Details",
        "HEADER_MOBILE_NO": "Mobile No",
        "HEADER_EMAIL": "Email",
        "HEADER_LOGIN_DETAILS": "Login Details",
        "HEADER_PASSWORD": "Password",
        "TEXT_DONT_HAVE_ACCOUNT": "I don't have an account",
        "SELECT_CADRE_LEVEL": "Select Cadre Level",
        "BTN_CANCEL": "Cancel",
        "CURRENT_PASSWORD": "Current Password",
        "ENTER_CURRENT_PASSWORD": "Enter Current Password",
        "ENTER_NEW_PASSWORD": "Enter New Password",
        "RETYPE_PASSWORD": "Retype Password",
        "TAKE_ASSESSMENT": "Take Assessment",
        "HEADER_NUTRITION_OUTCOME_DETAILS": "Nutrition Outcome Details",
        "VALIDATION_PHONE_NO": "Phone No must be 10 digit",
        "VERIFICATION_OTP_MESSAGE_ONE": "We have sent an OTP to your mobile number",
        "VERIFICATION_OTP_MESSAGE_TWO": "for verification purpose.",
        "BTN_VERIFY": "Verify",
        "LINK_RESEND_OTP": "Resend OTP",
        "LINK_CHANGE_MOBILE_NUMBER": "Change Mobile Number",
        "TEXT_INVALID_EMAIL": "Invalid email",
        "TEXT_APP_LANGUAGE": "App Language",
        "BTN_SUBMIT": "Submit",
        "BTN_GET_OTP": "Get OTP",
        "PLACEHOLDER_OTP": "OTP",
        "VALIDATION_CONFIRM_PASSWORD": "Passwords must match",
        "SCREENING_RESULT": "Screeing Result",
        "BTN_YES": "Yes",
        "BTN_NO": "No",
        "BTN_ALGORITHM_LINK": "Check Diagnostic Algorithm",
        "PULSE_RATE": "Pulse Rate",
        "NORMAL_RANGE": "Normal Range",
        "TEMPERATURE": "Temperature",
        "BLOOD_PRESSURE": "Blood Pressure",
        "RESPIRATORY_RATE": "Respiratory Rate",
        "OXYGEN_SATURATION": "Oxygen Saturation",
        "TEXT_BMI": "BMI",
        "TEXT_MUAC": "MUAC",
        "PEDAL_OEDEMA": "Pedal Oedema",
        "GENERAL_CONDITION": "General Condition",
        "TEXT_ICTERUS": "Icterus",
        "TEXT_HEMOGLOBIN": "Hemoglobin (HB)",
        "COUNT_WBC": "Total count of White Blood Cells",
        "TEXT_RBS": "Random blood sugar (RBS)",
        "TEXT_HIV": "HIV",
        "TEXT_XRAY": "Chest X ray",
        "TEXT_HEMOPTYSIS": "Hemoptysis",
        "TEXT_SCORE": "Score",
        "HEADER_LABORATORY_INVESTIGATION": "Assessment of TB patients",
        "BTN_CALCULATE_SCORE": "Calculate Score",
        "HEADER_LAB_SCORE": "Assessment of TB Patients' Investigation Score",
        "BTN_AVG_SCORE": "Back To Average Score",
        "BTN_Nutrition_Management": "Nutrition Management",
        "BTN_Nutrition_Next": "Next",
        "Differentiated_Care_Result_Title": "Score Result",
        "Differentiated_Care_Result_Thanks_Message": "Thank you for Assessment of TB Patient",
        "Differentiated_Care_High_Risk": "High Risk",
        "Differentiated_Care_Moderate_Risk": "Moderate Risk",
        "Differentiated_Care_Low_Risk": "Low Risk",
        "Differentiated_Care_Result_3": "Referring to DH/SDH or nearest secondary or tertiary care facility with availability of intensive care.",
        "Differentiated_Care_Result_2": "Referring to PHC or any facility with availability of MBBS doctor or facility indicated in referral column.",
        "Differentiated_Care_Result_1": "Providing intermediate care and observing for symptoms to subside.",
        "Btn_Differentiated_Care_Result": "View Detailed Score",
        "TITLE_DIFFERENTIANTED_CARE": "Differentiated Care Of TB Patients",
        "HEADER_EDIT_PROFILE": "Edit Profile",
        "BTN_UPDATE_PROFILE": "Update Profile",
        "EDIT_PROFILE_TEXT": "Edit Profile",
        "NO_DATA": "No Data",
        "BTN_UPDATE_APP": "Update",
        "BTN_OK": "ok",
        "ERROR_503_MESSAGE": "The server is temporarily down. try again later!",
        "ERROR_503_TITLE": "503 Service Unavailable",
        "CHAT_RELATED_OUESTION": "Related Quetions",
        "CHAT_MODULE_SUGGESTIONS": "Module Suggestions",
        "CHAT_ANSWERS": "Answers",
        "BOT_SUB_HEADER": "Hello! <br />I am Ni-kshay Setu. Let me know if you have any questions. You can select from the topics below or can type your question in the space provided.",
        "PLACEHOLDER_PATIENT_AGE": "Enter Patient Age",
        "PLACEHOLDER_PATIENT_NAME": "Enter Patient Name",
        "PLACEHOLDER_PATIENT_NIK_ID": "Enter Patient Nikshy ID",
        "PLACEHOLDER_PATIENT_GENDER": "Select Patient Gender",
        "OPTIONS_PATIENT_GENDER": "Male,Female,Other",
        "APP_LINK": "Share App Link",
        "HEADER_COUNTRY": "Country",
        "COMMUNITY_ENGAGEMENT_GUIDELINE": "Community Engagement",
        "PRIVACY_POLICY": "Privacy Policy",
        "CHAT_ADDITIONAL_MATERIAL": "Additional Resource Materials (Source of content: NTEP)",
        "CHAT_NTEP_ANSWERS": "Answers (Source of content: NTEP)",
        "TITLE_SURVEY_FORM": "Survey Form",
        "TITLE_LEADER_BOARD": "Leaderboard",
        "TITLE_RATING": "Rating",
        "TITLE_CERTIFICATES": "Certificates",
        "TITLE_NEAR_HEALTH_FACILITY": "Nearest Health Center",
        "F_CASE_FINDING": "Case Findings",
        "F_MANG_PATIENT": "Manage TB Patient",
        "F_REF_HEALTH_FACILITY": "Referal Health Facility",
        "F_RESO_MATERIAL": "Resource Material",
        "F_FEATURES": "Features",
        "N_NEWS_FEED": "News Feed",
        "SIMILAR_APPLI": "Similar Applications",
        "RECENTLY_ADDED": "Recently Added",
        "WE_R_KEEP_IMPROVING_YOUR_IMP_F_US": "We are always looking for ways to improve, your feedback is an important part of that process",
        "MODULE": "Module",
        "MORE_TOOLS": "More Tools",
        "U_HAVE_SUBMIT_ALL_FEEDBACK": "You have submitted all feedback.",
        "OTHER_SUGGESTIONS": "Other Suggestions",
        "SUBMIT": "Submit",
        "FEEDBACK": "Feedback",
        "COMPLETION_CERTIFICATE": "Completion Certificate",
        "AVAIL_FACILITIES": "Available Facilities",
        "LEVEL": "Level",
        "BRONZE": "Bronze",
        "GOLD": "Gold",
        "SILVER": "Silver",
        "OTHER_MODULES": "Other Modules",
        "TASKS": "Tasks",
        "MINUTES_SPENT": "Minutes Spent",
        "SUB_MODULE_VISITED": "Sub Module Visited",
        "CHATBOT_USAGE": "Chatbot Usage",
        "RESOURCE_MATERIAL_USAGE": "Resource Material Usage",
        "APP_OPENED": "App. Opened",
        "POINTS": "Points",
        "EDIT_PERSONAL_DETAILES": "Edit Personal Details",
        "EDIT_PROFILE_PICTURE": "Change Profile Picture",
        "CHANGE_APPLICATION_LANG": "Change Application Language",
        "SHARE_APP_LINK": "Share Application Link",
        "SIGN_OUT": "Sign Out",
        "UPDATE_DETAILS": "Update Details",
        "HEALTH_FACILITY": "Health Facility",
        "DISTRICT": "District",
        "CADER": "Cadre",
        "CADER_TYPE": "Cadre Type",
        "HEALTH_FACILITY_LVL": "Health-facility Level",
        "PERFORMANCE": "Performance",
        "CURRENT_ASSMNT": "Current Assessment",
        "PAST_ASSMNT": "Past Assessment",
        "FUTURE_ASSMNT": "Future Assessment",
        "CONFIRM_SUBMIT": "Confirm Submit",
        "ATTEMPTED": "Attempted",
        "SKIPPED": "Skipped",
        "OUT_OF_TOTAL": "Out Of Total",
        "VIEW": "View",
        "VIEW_CERTIFICATE": "View Certificate",
        "ASSESSMENT_NAME": "Assessment Name",
        "NO_OF_QUES": "No. of Quetion",
        "TIME_TO_COMPLETE": "Time to Complete",
        "COMPLETED_ON": "Completed on",
        "COMPLETION_RATE": "Completion Rate",
        "ASSESSMENT": "Assessment",
        "ACCURACY": "Accuracy",
        "CERTIFICATE": "Certificates",
        "DOWNLOAD": "Download",
        "ADD_PROF_PIC": "Add Profile Picture",
        "HEADER_CREATE_ACCOUNT": "Create Account",
        "HEADER_HEALTH_FACILITY": "Health Facility",
        "SEARCH_HEALTH_FACILITY": "Search Health Facility",
        "VIEW_ALL": "View All",
        "DETAILED_SCORE": "Detailed Score",
        "BRONZE_MEDAL": "Bronze Medal",
        "SILVER_MEDAL": "Silver Medal",
        "GOLD_MEDAL": "Gold Medal",
        "ASSESSMENT_COMPLETION_CERTI": "Assessment Certificates",
        "LEADERBOARD_INFOTAB_HEADER": "Leaderboard will nurture highly motivated users through a culture of recognition and gamified competitions. It will reinforce best in app performance by recognising accomplishments in interesting ways. Understand your application's progress, and by completing certain tasks, you will be rewarded with a medal to boost your efforts. The actions necessary to reach each level of overall performance are listed below along with information about those levels.",
        "TAB_NAME_LEADERBOARD": "Leaderboard",
        "TAB_NAME_TASKS": "Tasks",
        "TAB_NAME_ACHIEVEMENTS": "Achievements",
        "TAB_NAME_INFORMATION": "Information",
        "HEADER_SCREENING_TOOL": "Screening Tool",
        "THANK_U_FOR_THE_INPUTS": "Thank you for the inputs",
        "SELECT_AGE_WEIGHT_AND_HEIGHT": "Select age,weight and height",
        "SCREENING_HEADER_AGE_Y": "Age (Year)",
        "SCREENING_HEADER_WEIGHT_KG": "Weight (Kg)",
        "SCREENING_HEADER_HEIGHT_CM": "Height (cm)",
        "NEXT_BTN": "Next",
        "QUES_ARE_U_EXPERIENCING_ANY_SYMPTOMS": "Are you experiencing any of the following symptoms",
        "SCREENING_STEPER_LABEL_BASIC_INFO": "Basic Info.",
        "SCREENING_STEPER_LABEL_SYMPTOMS": "Symptoms",
        "HEADER_SURVEY_FORM": "Survey Form",
        "SURVEY_FORM_DESCRIPTION_TOP": "Survey form is developed to understand the requirements and feedback from the subscribers. It allows us to create the content most apprehensively needed for the Healthcare Personnel.",
        "SURVEY_FORM_DESCRIPTION_BOTTOM": "Please participate in this survey to build and enhance the capacity of NTEP workforce.",
        "HEADER_APP_LANG": "Application Language",
        "FOLLOW_US_ON_SOCIAL_MEDIA": "Follow us on social media",
        "FB_SOCIAL_MEDIA_NAME": "Ni-kshay.Setu",
        "INSTA_SOCIAL_MEDIA_NAME": "Ni-kshay.Setu",
        "WELCOME": "Welcome",
        "MASTER_SEARCH_TAB_MODULES": "Modules",
        "MASTER_SEARCH_TAB_SUB_MODULES": "Sub Modules",
        "MASTER_SEARCH_RESOURCE_MATERIAL": "Resource Material",
        "MASTER_SEARCH_TAB_FAQ": "FAQ",
        "TAB_ASSESS": "Assess",
        "NO_DATA_FUTURE_ASSESS": "No Result Found",
        "NO_DATA_PAST_ASSESS": "No Result Found",
        "NO_DATA_CURRENT_ASSESS": "No Result Found",
        "NO_DATA_SURVEY": "No Result Found",
        "NO_DATA_NOTIFICATION": "No Result Found",
        "Test_Treatment_Algo": "Test Treatment Algo",
        "Test_Diagnosis_Algorithm": "Test Diagnosis Algorithm",
        "Differentiated_Care_Normal_Risk": "No Risk",
        "TITLE_APP_INTE": "Application Interaction",
        "Active_case_findings_for_tb_patient": "Active Case Findings For TB Patient"
    },
    appMasterCms: [],
    dynamicAlogs: MODULE_LIST,
    appLang: 'en',
    appUnderMaintenance: false,
    platform: null,
    appStatus: {},
    flashNews: [
        {
            "id": 16295,
            "title": "Mobile Application comes in handy for healthcare workers as India chases target.",
            "description": "<p>New Delhi: A mobile application is\nhelping bridge the gap in\nknowledge regarding tuberculosis\nfor thousands of healthcare\nworkers as the Central\ngovernment strives to achieve its\nambitious target to reduce the TB\nburden by 2025. After its initial\nlaunch in January 2022, the \"Nikshay Setu\" app has helped over\n17,000 frontline healthcare\nworkers and other staff at the district, state and national levels to gain knowledge\nregarding various aspects of the disease, including diagnosis, treatment, and\nassessment of their training through digital modules, according to officials.\nAs per the World Health Organisation (WHO), the total number of incident TB\npatients (new and relapse) in 2021 in India was 19,33,381, a 19 percent rise. The Union government has set the aim to strategically reduce the TB burden in\nthe country by 2025, five years ahead of the Sustainable Development Goals,\nunder its National Tuberculosis Elimination Programme (NTEP).\n\"The Ni-kshay Setu application aims to boost the ability of healthcare workers to\ntreat the patients by helping reduce the knowledge gap regarding the disease,\"\nsaid Dr Harsh Shah, national coordinator of the TB project at the Gandhinagarbased Indian Institute of Public Health (IIPH) which developed it.\nSince the launch of the second and updated version of the app earlier this month,\nit is attracting nearly a thousand users per week, Shah told PTI.\nHe said the number of additions keeps growing as the app expands its base to\nserve the requirements of healthcare workers across 35 states and Union\nTerritories.\nThe need for the app was first felt after a survey covering 460 healthcare workers,\nmore than 900 TB patients, frontline workers, state and district TB officials and\nprivate doctors etc. in Gujarat and Jharkhand revealed gaps in their knowledge\nregarding the bacterial disease.\n\"The knowledge assessment showed the gaps ranging from 20-45 per cent\namong different cadres. Knowledge on patient management and new case\nfindings were the lowest scoring among all interviewed sections,\" Shah said.\nHe said the \"Ni-kshay Setu\" helps users to assess presumptive TB patients as per\ntheir details and symptoms and provides decision-making algorithms to arrive at\ntheir diagnosis and treatment regimen.\n\"It also provides a geospatial mapping of health facilities along with the availability\nof services. There is also an interactive artificial intelligence (AI)-based chatbot to\nanswer queries of users. This app is available in multiple languages with choice based learning and real-time patient-centric care,\" Shah said.\nAdditional Director of the Gujarat State TB Training and Demonstration Centre, Dr\nPankaj Nimavat said the app is particularly good regarding diagnosis and\ntreatment of the disease.\n\"Healthcare workers get to know where to refer the patients in case they suffer\nfrom adverse drug reactions and how to deal with the case,\" Nimavat said.\nHe said the app is also helping in capacity building for healthcare workers as part\nof the government's \"End TB Strategy\" by assessing workers and providing the As per the WHO's Global TB Report 2021, the estimated incidence of all forms of\nTB in India in 2020 was 188 per 100,000 population and the total number of\nincident TB patients (new and relapse) during 2021 was 19,33,381.\n&nbsp;<br></p><p style=\"margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-size: 12px; font-family: arial;\"><br style=\"margin: 0px; padding: 0px; font-family: Arial, Helvetica, sans-serif; font-size: 13px;\"></p><p style=\"margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-size: 12px; font-family: arial;\"><br></p>",
            "author": "PTI - The Economics Times",
            "source": "The Economics Times- Health World",
            "href": "https://health.economictimes.indiatimes.com/news/health-it/mobile-application-comes-in-handy-for-healthcare-workers-as-india-chases-target-to-reduce-tuberculosis-burden-by-2025/97219714?",
            "publish_date": "22 January 2023",
            "order_index": 1000,
            "active": 1,
            "deleted_at": null,
            "created_at": "2023-01-23T06:54:30.000000Z",
            "updated_at": "2023-04-18T04:55:46.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-news/16295",
            "media": []
        },
        {
            "id": 28872,
            "title": "India TB Report 2023",
            "description": null,
            "author": null,
            "source": "https://tbcindia.gov.in/",
            "href": "https://tbcindia.gov.in/showfile.php?lid=3680",
            "publish_date": "24/03/2023",
            "order_index": 1000,
            "active": 1,
            "deleted_at": null,
            "created_at": "2023-03-25T03:30:03.000000Z",
            "updated_at": "2023-03-31T05:16:18.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-news/28872",
            "media": []
        },
        {
            "id": 33792,
            "title": "PRIME MINISTER MODI MARKS THE START OF A NEW ERA ON WORLD TB DAY:YES! WE CAN END TB",
            "description": "<p><strong>GENEVA/VARANASI (24 March 2023)</strong> - The Stop TB Partnership today issued a positive World TB Day reset, ‘Yes! We Can End TB,’ to rally the international community to end tuberculosis (TB) by 2030. The Stop TB Partnership Board and partners convened for the first time during World TB Day in Varanasi, India - the country with the highest TB burden but also with high political commitment, ambition, hard work and a robust plan to end TB. On the sidelines of the One World TB Summit, the board and partners embraced a post-pandemic call to action that will see new efforts, research, tools and innovations put into practice.<br></p>",
            "author": null,
            "source": "https://www.stoptb.org/",
            "href": "https://www.stoptb.org/news/with-tb-response-rebounding-covid-19-pandemic-downturn-prime-minister-modi-marks-start-of-new",
            "publish_date": null,
            "order_index": 1000,
            "active": 1,
            "deleted_at": null,
            "created_at": "2023-04-16T13:46:46.000000Z",
            "updated_at": "2023-04-18T04:54:25.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-news/33792",
            "media": [
                {
                    "id": 1221,
                    "model_type": "App\\Models\\FlashNews",
                    "model_id": 33792,
                    "uuid": "e8df6f62-f56f-485f-bc4f-89965f06d2a6",
                    "collection_name": "flash_news_icon",
                    "name": "plTDXm2K11jW3JLhOThx5d4xQWFKYs0D9PdidXHR",
                    "file_name": "plTDXm2K11jW3JLhOThx5d4xQWFKYs0D9PdidXHR.jpg",
                    "mime_type": "image/jpeg",
                    "disk": "s3",
                    "conversions_disk": "s3",
                    "size": 162913,
                    "manipulations": [],
                    "custom_properties": {
                        "name": "unnamed_4.jpg",
                        "width": 1251,
                        "height": 834,
                        "file_name": "unnamed_4.jpg"
                    },
                    "generated_conversions": {
                        "thumb_200": true
                    },
                    "responsive_images": [],
                    "order_column": 1157,
                    "created_at": "2023-04-16T13:47:31.000000Z",
                    "updated_at": "2023-04-16T13:47:32.000000Z",
                    "original_url": "https://api.nikshay-setu.in/media/1221/plTDXm2K11jW3JLhOThx5d4xQWFKYs0D9PdidXHR.jpg",
                    "preview_url": ""
                }
            ]
        },
        {
            "id": 76,
            "title": "Global Tuberculosis Report 2022",
            "description": "Each year, the WHO Global TB Report provides a comprehensive and up-to-date assessment of the TB epidemic, and of progress in prevention, diagnosis and treatment of the disease, at global, regional and country levels. This is done in the context of global...",
            "author": null,
            "source": "https://www.who.int/teams/global-tuberculosis-programme/tb-reports",
            "href": "https://www.who.int//publications/i/item/9789240061729",
            "publish_date": "Featured publication | 27 October 2022",
            "order_index": 100,
            "active": 1,
            "deleted_at": null,
            "created_at": "2022-10-28T04:45:19.000000Z",
            "updated_at": "2023-04-18T04:56:43.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-news/76",
            "media": [
                {
                    "id": 1006,
                    "model_type": "App\\Models\\FlashNews",
                    "model_id": 76,
                    "uuid": "4100a137-9274-4898-9e3b-ea6dc3922390",
                    "collection_name": "flash_news_icon",
                    "name": "DJ0WDEk7BA0nj0945IJiyffXIwMOQcCXoRcpbE3U",
                    "file_name": "DJ0WDEk7BA0nj0945IJiyffXIwMOQcCXoRcpbE3U.png",
                    "mime_type": "image/png",
                    "disk": "s3",
                    "conversions_disk": "s3",
                    "size": 6220,
                    "manipulations": [],
                    "custom_properties": {
                        "name": "a88d12928ece8657bfc27bdfb4da6ec3 1.png",
                        "width": 90,
                        "height": 72,
                        "file_name": "a88d12928ece8657bfc27bdfb4da6ec3 1.png"
                    },
                    "generated_conversions": {
                        "thumb_200": true
                    },
                    "responsive_images": [],
                    "order_column": 977,
                    "created_at": "2022-12-20T05:18:53.000000Z",
                    "updated_at": "2022-12-20T05:18:53.000000Z",
                    "original_url": "https://api.nikshay-setu.in/media/1006/DJ0WDEk7BA0nj0945IJiyffXIwMOQcCXoRcpbE3U.png",
                    "preview_url": ""
                }
            ]
        },
        {
            "id": 1,
            "title": "Pradhan Mantri TB Mukt Bharat Abhiyaan",
            "description": "<p><br></p><p><br></p><p>PDF -&nbsp;<a href=\"https://tbcindia.gov.in/showfile.php?lid=3672\" style=\"background-color: rgb(255, 255, 255); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 0.875rem;\">https://tbcindia.gov.in/showfile.php?lid=3672</a></p>",
            "author": null,
            "source": "https://tbcindia.gov.in/",
            "href": "https://tbcindia.gov.in/index1.php?lang=1&level=1&sublinkid=5629&lid=3670",
            "publish_date": "09/09/2022",
            "order_index": 10,
            "active": 1,
            "deleted_at": null,
            "created_at": "2022-10-28T04:45:17.000000Z",
            "updated_at": "2023-04-18T04:52:37.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-news/1",
            "media": [
                {
                    "id": 1004,
                    "model_type": "App\\Models\\FlashNews",
                    "model_id": 1,
                    "uuid": "6c2670af-1a06-4a0c-9cac-e7d393ec34b1",
                    "collection_name": "flash_news_icon",
                    "name": "skGJoKIC4BNSDLmxX6Th76tu7tMZNXhJHBVazGfS",
                    "file_name": "skGJoKIC4BNSDLmxX6Th76tu7tMZNXhJHBVazGfS.jpg",
                    "mime_type": "image/jpeg",
                    "disk": "s3",
                    "conversions_disk": "s3",
                    "size": 22819,
                    "manipulations": [],
                    "custom_properties": {
                        "name": "pRhMGWnE_400x400.jpg",
                        "width": 400,
                        "height": 400,
                        "file_name": "pRhMGWnE_400x400.jpg"
                    },
                    "generated_conversions": {
                        "thumb_200": true
                    },
                    "responsive_images": [],
                    "order_column": 975,
                    "created_at": "2022-12-20T05:16:45.000000Z",
                    "updated_at": "2022-12-20T05:16:46.000000Z",
                    "original_url": "https://api.nikshay-setu.in/media/1004/skGJoKIC4BNSDLmxX6Th76tu7tMZNXhJHBVazGfS.jpg",
                    "preview_url": ""
                }
            ]
        },
        {
            "id": 1598,
            "title": "Disease A-Z Tuberculosis",
            "description": null,
            "author": null,
            "source": "https://www.nhp.gov.in/disease/respiratory/lungs/tuberculosis",
            "href": "https://www.nhp.gov.in/disease/respiratory/lungs/tuberculosis",
            "publish_date": null,
            "order_index": 6,
            "active": 1,
            "deleted_at": null,
            "created_at": "2022-12-06T11:02:43.000000Z",
            "updated_at": "2023-01-23T07:08:56.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-news/1598",
            "media": [
                {
                    "id": 1007,
                    "model_type": "App\\Models\\FlashNews",
                    "model_id": 1598,
                    "uuid": "60604c5e-6373-44b4-b6d0-a4f4186f47a3",
                    "collection_name": "flash_news_icon",
                    "name": "CK4Krm02QhA09pmaFYRijoc4BEKsQLnfFMHgSC3B",
                    "file_name": "CK4Krm02QhA09pmaFYRijoc4BEKsQLnfFMHgSC3B.png",
                    "mime_type": "image/png",
                    "disk": "s3",
                    "conversions_disk": "s3",
                    "size": 102759,
                    "manipulations": [],
                    "custom_properties": {
                        "name": "download (1) 2.png",
                        "width": 360,
                        "height": 360,
                        "file_name": "download (1) 2.png"
                    },
                    "generated_conversions": {
                        "thumb_200": true
                    },
                    "responsive_images": [],
                    "order_column": 978,
                    "created_at": "2022-12-20T05:19:36.000000Z",
                    "updated_at": "2022-12-20T05:19:36.000000Z",
                    "original_url": "https://api.nikshay-setu.in/media/1007/CK4Krm02QhA09pmaFYRijoc4BEKsQLnfFMHgSC3B.png",
                    "preview_url": ""
                }
            ]
        },
        {
            "id": 11171,
            "title": "People with diabetes",
            "description": "<div data-contents=\"true\"><div class=\"\" data-block=\"true\" data-editor=\"d2o81\" data-offset-key=\"aomqi-0-0\"><div data-offset-key=\"aomqi-0-0\" class=\"public-DraftStyleDefault-block public-DraftStyleDefault-ltr\"><span data-offset-key=\"aomqi-0-0\"><span data-text=\"true\">Treatment and case management of TB in people with diabetes should be provided in accordance with existing TB treatment guidelines and international standards. The same TB treatment regimen should be prescribed to people with diabetes as for people without diabetes. </span></span></div></div></div>",
            "author": null,
            "source": "https://tbksp.org/en/recommendation/page-1",
            "href": "https://who.tuberculosis.recmap.org/recommendation/252c931d-758b-4f35-a20c-9d9b47b14834",
            "publish_date": "27 October 2022",
            "order_index": 4,
            "active": 1,
            "deleted_at": null,
            "created_at": "2022-12-30T03:30:10.000000Z",
            "updated_at": "2023-01-23T07:08:30.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-news/11171",
            "media": []
        },
        {
            "id": 11184,
            "title": "Overcoming the drug-resistant TB crisis in children and adolescents",
            "description": "<p style=\"text-align: justify; \">Tuberculosis (TB) is a preventable and curable disease, but it continues to impact the lives and development of millions of children and adolescents. Children and young adolescents aged under 15 years represent about 11% of all people with TB globally. This means 1.1 million children and young adolescents aged under 15 years fall ill with TB every year, and more than 225 000 of them lose their lives.</p><p style=\"text-align: justify; \">The Updated guidelines on Management of tuberculosis in children and adolescents include new recommendations that cover diagnostic approaches for TB, shorter treatment for children with non-severe drug-susceptible TB, a new option for the treatment of TB meningitis, the use of bedaquiline and delamanid in young children with multidrug- and rifampicin-resistant TB and decentralized and family-centred, integrated models of care for TB case detection and prevention in children and adolescents.</p>",
            "author": "World Health Organization",
            "source": "https://www.who.int/publications/i/item/9789240046764",
            "href": "https://www.who.int/publications/i/item/9789240046764",
            "publish_date": "21 September 2022",
            "order_index": 3,
            "active": 1,
            "deleted_at": null,
            "created_at": "2022-12-30T09:46:14.000000Z",
            "updated_at": "2023-01-23T06:58:43.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-news/11184",
            "media": [
                {
                    "id": 1029,
                    "model_type": "App\\Models\\FlashNews",
                    "model_id": 11184,
                    "uuid": "50e306f5-1670-442c-9b93-d09893975a93",
                    "collection_name": "flash_news_icon",
                    "name": "3refnfEWAczVfqFJndnXO0nxsFLTQlu1ZzGjOoaU",
                    "file_name": "3refnfEWAczVfqFJndnXO0nxsFLTQlu1ZzGjOoaU.png",
                    "mime_type": "image/png",
                    "disk": "s3",
                    "conversions_disk": "s3",
                    "size": 125071,
                    "manipulations": [],
                    "custom_properties": {
                        "name": "9789240046764-eng-pdf.png",
                        "width": 448,
                        "height": 420,
                        "file_name": "9789240046764-eng-pdf.png"
                    },
                    "generated_conversions": {
                        "thumb_200": true
                    },
                    "responsive_images": [],
                    "order_column": 997,
                    "created_at": "2022-12-30T09:46:57.000000Z",
                    "updated_at": "2022-12-30T09:46:57.000000Z",
                    "original_url": "https://api.nikshay-setu.in/media/1029/3refnfEWAczVfqFJndnXO0nxsFLTQlu1ZzGjOoaU.png",
                    "preview_url": ""
                }
            ]
        },
        {
            "id": 1387,
            "title": "Tuberculosis",
            "description": "Key facts A total of 1.6 million people died from TB in 2021 (including 187 000 people with HIV). Worldwide, TB is the 13th leading cause of death and the second leading infectious killer after COVID-19 (above HIV/AIDS). In 2021, an estimated 10.6 million people fell ill with tuberculosis(TB) worldwide. Six million men, 3.4 million women and 1.2 million children. TB is present in all countries and age groups. But TB is curable and preventable. In 2021, 1.2 million children fell ill with TB globally. Child and adolescent TB is often overlooked by health providers and can be difficult to diagnose and treat. In 2021, the 30 high TB burden countries accounted for 87% of new TB cases Multidrug-resistant TB (MDR-TB) remains a public health crisis and a health security threat. Only about one in three people with drug resistant TB accessed treatment in 2020. Globally, TB incidence is falling at about 2% per year and between 2015 and 2020 the cumulative reduction was 11%. This was over half way to the End TB Strategy milestone of 20% reduction between 2015 and 2020. An estimated 66 million lives were saved through TB diagnosis and treatment between 2000 and 2020. Globally, close to one in two TB-affected households face costs higher than 20% of their household income, according to latest national TB patient cost survey data. The world did not reach the milestone of 0% TB patients and their households facing catastrophic costs as a result of TB disease by 2020. By 2022, US$ 13 billion is needed annually for TB prevention, diagnosis, treatment and care to achieve the global target agreed at the UN high level-meeting on TB in 2018. Funding in low- and middle-income countries (LMICs) that account for 98% of reported TB cases falls far short of what is needed. Spending in 2020 amounted to US$ 5.3 billion less than half (41%) of the global target. There was an 8.7% decline in spending between 2019 and 2020 (from US$ 5.8 billion to US$ 5.3 billion), with TB funding in 2020 back to the level of 2016. Ending the TB epidemic by 2030 is among the health targets of the United Nations Sustainable Development Goals (SDGs).",
            "author": null,
            "source": "https://www.who.int/news-room/fact-sheets/detail/tuberculosis",
            "href": "https://www.who.int/news-room/fact-sheets/detail/tuberculosis",
            "publish_date": "27 October 2022",
            "order_index": 2,
            "active": 1,
            "deleted_at": null,
            "created_at": "2022-12-06T11:02:40.000000Z",
            "updated_at": "2023-01-23T07:08:15.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-news/1387",
            "media": [
                {
                    "id": 1005,
                    "model_type": "App\\Models\\FlashNews",
                    "model_id": 1387,
                    "uuid": "e4490a7d-3ee7-4e8e-a2ee-ac288e82f92d",
                    "collection_name": "flash_news_icon",
                    "name": "bPOoXs8VsTvvCFg9YrRbiXFsymNn8wavzT97CrNC",
                    "file_name": "bPOoXs8VsTvvCFg9YrRbiXFsymNn8wavzT97CrNC.png",
                    "mime_type": "image/png",
                    "disk": "s3",
                    "conversions_disk": "s3",
                    "size": 169762,
                    "manipulations": [],
                    "custom_properties": {
                        "name": "download 3.png",
                        "width": 360,
                        "height": 360,
                        "file_name": "download 3.png"
                    },
                    "generated_conversions": {
                        "thumb_200": true
                    },
                    "responsive_images": [],
                    "order_column": 976,
                    "created_at": "2022-12-20T05:18:11.000000Z",
                    "updated_at": "2022-12-20T05:18:12.000000Z",
                    "original_url": "https://api.nikshay-setu.in/media/1005/bPOoXs8VsTvvCFg9YrRbiXFsymNn8wavzT97CrNC.png",
                    "preview_url": ""
                }
            ]
        }
    ],
    appLanggusges: [{ title: "English", code: "en" }, { title: 'हिंदी', code: 'hi' }, { title: 'ગુજરાતી', code: 'gu' }, { title: 'मराठी', code: 'mr' }],
    allSimilarApps: [
        {
            "id": 1,
            "title": "Ni-kshay",
            "sub_title": "National TB Elimination Program (NTEP)",
            "href": "org.rntcp.nikshay",
            "href_web": "https://www.nikshay.in/",
            "href_ios": "https://www.nikshay.in/",
            "order_index": 1,
            "active": 1,
            "deleted_at": null,
            "created_at": "2022-10-28T05:05:26.000000Z",
            "updated_at": "2022-12-20T05:01:07.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-similar-apps/1",
            "media": [
                {
                    "id": 992,
                    "model_type": "App\\Models\\FlashSimilarApp",
                    "model_id": 1,
                    "uuid": "d143b4a2-09de-4da1-bbdc-8c3a75ba3dc7",
                    "collection_name": "flash_app_icon",
                    "name": "uOE1A2T2NTU11Lky8f9o32mTGDEObbIQ3DnSlFGH",
                    "file_name": "uOE1A2T2NTU11Lky8f9o32mTGDEObbIQ3DnSlFGH.png",
                    "mime_type": "image/png",
                    "disk": "s3",
                    "conversions_disk": "s3",
                    "size": 30967,
                    "manipulations": [],
                    "custom_properties": {
                        "name": "nikshay.png",
                        "width": 360,
                        "height": 360,
                        "file_name": "nikshay.png"
                    },
                    "generated_conversions": {
                        "thumb_200": true
                    },
                    "responsive_images": [],
                    "order_column": 963,
                    "created_at": "2022-12-20T04:45:20.000000Z",
                    "updated_at": "2022-12-20T04:45:20.000000Z",
                    "original_url": "https://api.nikshay-setu.in/media/992/uOE1A2T2NTU11Lky8f9o32mTGDEObbIQ3DnSlFGH.png",
                    "preview_url": ""
                }
            ]
        },
        {
            "id": 2,
            "title": "TB Aarogya Sathi",
            "sub_title": "N",
            "href": "com.tb.aarogya.sathi",
            "href_web": "https://play.google.com/store/apps/details?id=com.tb.aarogya.sathi&hl=en_IN&gl=US",
            "href_ios": "https://tbcindia.gov.in/index1.php?lang=1&level=1&sublinkid=5527&lid=3591",
            "order_index": 2,
            "active": 1,
            "deleted_at": null,
            "created_at": "2022-10-28T05:09:00.000000Z",
            "updated_at": "2022-12-20T04:52:00.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-similar-apps/2",
            "media": [
                {
                    "id": 994,
                    "model_type": "App\\Models\\FlashSimilarApp",
                    "model_id": 2,
                    "uuid": "d9e9e5ba-c1ef-44df-b5c7-bcc6730d54d1",
                    "collection_name": "flash_app_icon",
                    "name": "0BESNwyX4ne3yRgmjVRiq0nK12MaShAdgDfc1a28",
                    "file_name": "0BESNwyX4ne3yRgmjVRiq0nK12MaShAdgDfc1a28.png",
                    "mime_type": "image/png",
                    "disk": "s3",
                    "conversions_disk": "s3",
                    "size": 62924,
                    "manipulations": [],
                    "custom_properties": {
                        "name": "aarogya.png",
                        "width": 360,
                        "height": 360,
                        "file_name": "aarogya.png"
                    },
                    "generated_conversions": {
                        "thumb_200": true
                    },
                    "responsive_images": [],
                    "order_column": 965,
                    "created_at": "2022-12-20T04:52:00.000000Z",
                    "updated_at": "2022-12-20T04:52:00.000000Z",
                    "original_url": "https://api.nikshay-setu.in/media/994/0BESNwyX4ne3yRgmjVRiq0nK12MaShAdgDfc1a28.png",
                    "preview_url": ""
                }
            ]
        },
        {
            "id": 3,
            "title": "Nikshay Aushadhi",
            "sub_title": "n",
            "href": "com.cdac.DWH",
            "href_web": "https://www.nikshayaushadhi.in/IMCS/hissso/loginLogin.imcs",
            "href_ios": "https://www.nikshayaushadhi.in/IMCS/hissso/loginLogin.imcs",
            "order_index": 3,
            "active": 1,
            "deleted_at": null,
            "created_at": "2022-12-05T12:58:57.000000Z",
            "updated_at": "2022-12-20T04:59:29.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-similar-apps/3",
            "media": [
                {
                    "id": 998,
                    "model_type": "App\\Models\\FlashSimilarApp",
                    "model_id": 3,
                    "uuid": "d02f6fb6-a7ba-4ac1-afc1-b0ea009fb2b1",
                    "collection_name": "flash_app_icon",
                    "name": "GUEsr6IJmyeblZmJ3EUiK4otiBWrsngEC15pqbSu",
                    "file_name": "GUEsr6IJmyeblZmJ3EUiK4otiBWrsngEC15pqbSu.png",
                    "mime_type": "image/png",
                    "disk": "s3",
                    "conversions_disk": "s3",
                    "size": 31354,
                    "manipulations": [],
                    "custom_properties": {
                        "name": "unnamed 2.png",
                        "width": 200,
                        "height": 200,
                        "file_name": "unnamed 2.png"
                    },
                    "generated_conversions": {
                        "thumb_200": true
                    },
                    "responsive_images": [],
                    "order_column": 969,
                    "created_at": "2022-12-20T04:59:28.000000Z",
                    "updated_at": "2022-12-20T04:59:29.000000Z",
                    "original_url": "https://api.nikshay-setu.in/media/998/GUEsr6IJmyeblZmJ3EUiK4otiBWrsngEC15pqbSu.png",
                    "preview_url": ""
                }
            ]
        },
        {
            "id": 4,
            "title": "AB-HWC",
            "sub_title": "h",
            "href": "gov.mohfw.abhwc",
            "href_web": "http://ab-hwc.nhp.gov.in/",
            "href_ios": "https://apps.apple.com/in/app/ab-hwc/id1550252728",
            "order_index": 4,
            "active": 1,
            "deleted_at": null,
            "created_at": "2022-12-05T12:59:37.000000Z",
            "updated_at": "2022-12-20T05:04:07.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-similar-apps/4",
            "media": [
                {
                    "id": 999,
                    "model_type": "App\\Models\\FlashSimilarApp",
                    "model_id": 4,
                    "uuid": "98b9ab84-5597-43b6-9bd4-6ef01f9fb7d4",
                    "collection_name": "flash_app_icon",
                    "name": "9oAnCfE0cK4PD9CkZgz8xKvP05L9vTpJojqEwwX8",
                    "file_name": "9oAnCfE0cK4PD9CkZgz8xKvP05L9vTpJojqEwwX8.png",
                    "mime_type": "image/png",
                    "disk": "s3",
                    "conversions_disk": "s3",
                    "size": 117630,
                    "manipulations": [],
                    "custom_properties": {
                        "name": "unnamed 1.png",
                        "width": 360,
                        "height": 360,
                        "file_name": "unnamed 1.png"
                    },
                    "generated_conversions": {
                        "thumb_200": true
                    },
                    "responsive_images": [],
                    "order_column": 970,
                    "created_at": "2022-12-20T05:04:07.000000Z",
                    "updated_at": "2022-12-20T05:04:07.000000Z",
                    "original_url": "https://api.nikshay-setu.in/media/999/9oAnCfE0cK4PD9CkZgz8xKvP05L9vTpJojqEwwX8.png",
                    "preview_url": ""
                }
            ]
        },
        {
            "id": 5,
            "title": "eSanjeevani",
            "sub_title": "N",
            "href": "in.hied.esanjeevaniopd",
            "href_web": "https://esanjeevani.in/",
            "href_ios": "https://esanjeevani.in/",
            "order_index": 5,
            "active": 1,
            "deleted_at": null,
            "created_at": "2022-12-05T13:00:30.000000Z",
            "updated_at": "2022-12-20T05:05:37.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-similar-apps/5",
            "media": [
                {
                    "id": 1000,
                    "model_type": "App\\Models\\FlashSimilarApp",
                    "model_id": 5,
                    "uuid": "4721903b-2790-45db-bbf9-433465718bd1",
                    "collection_name": "flash_app_icon",
                    "name": "qEP1HYJ1nZqWowjkz6X2bPQidwXfc88Rtp9rf5XF",
                    "file_name": "qEP1HYJ1nZqWowjkz6X2bPQidwXfc88Rtp9rf5XF.png",
                    "mime_type": "image/png",
                    "disk": "s3",
                    "conversions_disk": "s3",
                    "size": 90116,
                    "manipulations": [],
                    "custom_properties": {
                        "name": "eswasthya.png",
                        "width": 360,
                        "height": 360,
                        "file_name": "eswasthya.png"
                    },
                    "generated_conversions": {
                        "thumb_200": true
                    },
                    "responsive_images": [],
                    "order_column": 971,
                    "created_at": "2022-12-20T05:05:37.000000Z",
                    "updated_at": "2022-12-20T05:05:37.000000Z",
                    "original_url": "https://api.nikshay-setu.in/media/1000/qEP1HYJ1nZqWowjkz6X2bPQidwXfc88Rtp9rf5XF.png",
                    "preview_url": ""
                }
            ]
        },
        {
            "id": 6,
            "title": "Aarogya Setu",
            "sub_title": "A",
            "href": "nic.goi.aarogyasetu",
            "href_web": "https://www.aarogyasetu.gov.in/",
            "href_ios": "https://www.aarogyasetu.gov.in/",
            "order_index": 6,
            "active": 1,
            "deleted_at": null,
            "created_at": "2022-12-05T13:17:11.000000Z",
            "updated_at": "2023-01-09T01:06:30.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-similar-apps/6",
            "media": [
                {
                    "id": 1001,
                    "model_type": "App\\Models\\FlashSimilarApp",
                    "model_id": 6,
                    "uuid": "9b40f688-ab36-48be-9232-0e86881adf7e",
                    "collection_name": "flash_app_icon",
                    "name": "80ZQUVBZGzrYD0Q0xhY2snLmbW2BoGc2DKpVe4Vu",
                    "file_name": "80ZQUVBZGzrYD0Q0xhY2snLmbW2BoGc2DKpVe4Vu.png",
                    "mime_type": "image/png",
                    "disk": "s3",
                    "conversions_disk": "s3",
                    "size": 81350,
                    "manipulations": [],
                    "custom_properties": {
                        "name": "aarogya setu.png",
                        "width": 360,
                        "height": 360,
                        "file_name": "aarogya setu.png"
                    },
                    "generated_conversions": {
                        "thumb_200": true
                    },
                    "responsive_images": [],
                    "order_column": 972,
                    "created_at": "2022-12-20T05:06:34.000000Z",
                    "updated_at": "2022-12-20T05:06:34.000000Z",
                    "original_url": "https://api.nikshay-setu.in/media/1001/80ZQUVBZGzrYD0Q0xhY2snLmbW2BoGc2DKpVe4Vu.png",
                    "preview_url": ""
                }
            ]
        },
        {
            "id": 7,
            "title": "NISHTHA iLearn",
            "sub_title": "I",
            "href": "com.ast.ilearn",
            "href_web": "com.ast.ilearn",
            "href_ios": "https://play.google.com/store/apps/details?id=com.ast.ilearn&hl=en_IN&gl=US",
            "order_index": 7,
            "active": 1,
            "deleted_at": null,
            "created_at": "2022-12-05T13:18:04.000000Z",
            "updated_at": "2022-12-20T05:13:04.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-similar-apps/7",
            "media": [
                {
                    "id": 1002,
                    "model_type": "App\\Models\\FlashSimilarApp",
                    "model_id": 7,
                    "uuid": "6ff3f189-13a5-49d1-b411-a501ee974c07",
                    "collection_name": "flash_app_icon",
                    "name": "1inbe1cW2QSroPtC8n6khBz8yuaXVDjz3yvPb1ag",
                    "file_name": "1inbe1cW2QSroPtC8n6khBz8yuaXVDjz3yvPb1ag.png",
                    "mime_type": "image/png",
                    "disk": "s3",
                    "conversions_disk": "s3",
                    "size": 59298,
                    "manipulations": [],
                    "custom_properties": {
                        "name": "disha.png",
                        "width": 360,
                        "height": 360,
                        "file_name": "disha.png"
                    },
                    "generated_conversions": {
                        "thumb_200": true
                    },
                    "responsive_images": [],
                    "order_column": 973,
                    "created_at": "2022-12-20T05:13:04.000000Z",
                    "updated_at": "2022-12-20T05:13:04.000000Z",
                    "original_url": "https://api.nikshay-setu.in/media/1002/1inbe1cW2QSroPtC8n6khBz8yuaXVDjz3yvPb1ag.png",
                    "preview_url": ""
                }
            ]
        },
        {
            "id": 8,
            "title": "Standard Treatment Workflows",
            "sub_title": "S",
            "href": "com.duretechnologies.apps.android.stws",
            "href_web": "https://stw.icmr.org.in/",
            "href_ios": "https://apps.apple.com/in/app/standard-treatment-workflows/id1487467141",
            "order_index": 8,
            "active": 1,
            "deleted_at": null,
            "created_at": "2022-12-05T13:18:52.000000Z",
            "updated_at": "2022-12-20T05:42:52.000000Z",
            "resource_url": "https://api.nikshay-setu.in/admin/flash-similar-apps/8",
            "media": [
                {
                    "id": 1003,
                    "model_type": "App\\Models\\FlashSimilarApp",
                    "model_id": 8,
                    "uuid": "b454d5c7-f64c-413d-8049-15dc10d80833",
                    "collection_name": "flash_app_icon",
                    "name": "IVy1wBQYiGLNxoNmqzbu8rOZsEJ2dfrxmD0ffHFZ",
                    "file_name": "IVy1wBQYiGLNxoNmqzbu8rOZsEJ2dfrxmD0ffHFZ.png",
                    "mime_type": "image/png",
                    "disk": "s3",
                    "conversions_disk": "s3",
                    "size": 30882,
                    "manipulations": [],
                    "custom_properties": {
                        "name": "stw.png",
                        "width": 360,
                        "height": 360,
                        "file_name": "stw.png"
                    },
                    "generated_conversions": {
                        "thumb_200": true
                    },
                    "responsive_images": [],
                    "order_column": 974,
                    "created_at": "2022-12-20T05:14:32.000000Z",
                    "updated_at": "2022-12-20T05:14:32.000000Z",
                    "original_url": "https://api.nikshay-setu.in/media/1003/IVy1wBQYiGLNxoNmqzbu8rOZsEJ2dfrxmD0ffHFZ.png",
                    "preview_url": ""
                }
            ]
        }
    ],
    feedBackDetails: [],
    isFeedbackModal: false,
    topModules: [{
        "most_usefull": [
            {
                "title": "Case Definition",
                "type": "Case Definition",
                "icon": "learning.svg",
                "link": "AlgorithmList",
                "activityType": "module_case_defintion"
            },
            {
                "title": "Guidance on ADR",
                "type": "Guidance on ADR",
                "icon": "adr.svg",
                "link": "AlgorithmList",
                "activityType": "module_guidance_on_adr"
            },
            {
                "title": "Diagnostic Care Cascade",
                "type": "Diagnosis Algorithm",
                "icon": "algorithm.svg",
                "link": "AlgorithmList",
                "activityType": "module_diagnostic_care_cascade"
            },
            {
                "title": "Treatment Care Cascade",
                "type": "Treatment Algorithm",
                "icon": "treatment.svg",
                "link": "AlgorithmList",
                "activityType": "module_treatment_care_cascade"
            }
        ]
    }],
    recentlyAdded: [],
    appTime: null,
    isScrolling: true,
    notificationObj: {},
    tourLoader: false,
    dynamicAlogsloader: false,
    tourSlider: [],
    oldTourIds: [],
    notificationList: [],
    notificationObj: {}
}


export const M_masterSearch = {
    loader: false,
    moduleLoader: false,
    subModuleLoader: false,
    rmLoader: false,
    faqLoader: false,
    masterSearchData: {},
    moduleData: [],
    subModuleData: [],
    rmData: [],
    faqData: []
}
export const M_survey = {
    loader: false,
    QuestionList: [],
    SurveyList: [],
}


export const M_user = {
    loader: false,
    State: [],
    allDistricts: [],
    allBlocks: [],
    allCadres: [],
    allCadresType: [],
    allHealths: [],
    userData: [],
}

export const M_auth = {
    authErrors: {},
    loader: false,
    authUser: null,
    token: null,
}

export const M_assessment = {
    loader: false,
    allAssessment: [],
    assessmentQuestions: [],
    userAssessmentResult: [],
    userPastAssessments: [],
    futureAssessments: [],
    assessmentPerformance: [],
}

export const M_materials = {
    loader: false,
    materialsList: [],
    rootFolders: [],
}

export const M_algorithm = {
    loader: false,
    algorithmMasterNodes: [],
    algorithmDependentNodes: {},
    algorithmFlow: [],
    algoNodes: {},
}

export const M_cgc = {
    loader: false,
    allChapters: [],
    allChaptersById: [],
}

export const M_screening = {
    loader: false,
    symptomsList: [],
}
export const M_health = {
    loader: false,
    filterDetails: [],
    filterObj: {},
    stateID: -1,
    districtID: -1,
    blockID: -1,
    facility: '',
    filterPage: 1,
    searchTerm: '',
    sortBy: 'ASC',
}

export const M_chat = {
    chatloader: false,
    currentKeywordObj: {},
    questionHitLoader: false,
    chatArray: [],
    feedBackArray: [],
    questionActivityId: '',
}

export const M_leaderBoard = {
    loader: false,
    listData: {},
    lederBoardList: [],
    lederBoardTaskList: {},
    achivement: {},
    allCertificates: [],
}