import { DarkTheme, DefaultTheme } from '@react-navigation/native';
import { RFValue } from 'react-native-responsive-fontsize';

export const appTheme = {
    colors: {
        ...DefaultTheme.colors,
        black: '#000000',
        black2: '#100F0F',
        white: '#FFFFFF',
        primary: '#5584AC',
        secondary: '#FA967E',
        error: '#FF6B6B',
        success: '#56D6C7',
        warning: '#FF7D7D',
        Blue_2: '#5584AC',
        Blue_Theme: '#22577E',
        lightBlue3: '#95CDFE',
        Grey_3: '#707070',
        Grey_1: '#DFDEDE',
        Grey_2: '#F5F5F5',
        Grey_4: '#808080',
        Card_Gradian: '#13B0DB',
        ORANGE: '#FA967E',
        YELLOW: '#F6F2D4',
        HOVER_ORANGE: '#FFC18E',
        Card_2: '#94A5E2',
        Card_3: '#E29B2F',
        Card_4: '#EDFFF1',
        Notification_red: '#FF7D7D',
        Light_blue: '#ECF6FF',
        Blue_Gradient: ['#8FC9FB', '#5889B4'],
        green: '#2A91A8',
        Feed_Gradient: ['#22577e13', '#ffffff00'],
        cyanBlue: '#CAF2FF',
        purple_light: '#F9F9FF',
        cream: '#FFF5ED',
        tealGreen: '#0D9488',
        brightYellow: '#FFD12D',
        CorrectGreen: '#BDFFC8',

    },
    lightcolors: {
        colors: {
            ...DefaultTheme.colors,
            achivementBackground: '#E5F4FF',
            P: '#707070',
            chatHeaderBack: '#ECF6FF',
            chatBackground: '#587AB4',
            BorderColor: '#DFDEDE',
            accountlinkBack: '#F9F9FF',
            dropDownText: '#707070',
            dropDownBack: '#FFFFFF',
            dropDownSelectBack: '#DFDEDE',
            tabActive: '#FA967E',
            tabInActive: '#22577E',
            certificateHeaderBack: '#ECF6FF',
            certificateHeader: '#22577E',
            certiSubHeaderBack: '#FFF',
            certiSubHeaderTitle: '#13B0DB',
            assessPointBackground: '#ECF6FF',
            assessPointText: '#5584AC',
            CircularProgressInactive: '#F5F5F5',
            cardBackground: '#FFFFFF',
            cardBackground2: '#13B0DB',
            assessmentTitle: '#22577E',
            bottomBorder: '#ddd',
            headertext: '#FFF',
            headerBackground: '#5584AC',
            MasterBackground: '#FFFFFF',
            cardBorder: '#ECF6FF',
            titleOrange: '#100F0F',
            background: '#FFFFFF',
            black: '#000000',
            black2: '#100F0F',
            white: '#FFFFFF',
            primary: '#5584AC',
            secondary: '#FA967E',
            error: '#FF6B6B',
            success: '#56D6C7',
            warning: '#FF7D7D',
            Blue_2: '#5584AC',
            Blue_Theme: '#22577E',
            lightBlue3: '#95CDFE',
            Grey_3: '#707070',
            Grey_1: '#DFDEDE',
            Grey_2: '#F5F5F5',
            Grey_4: '#808080',
            Card_Gradian: '#13B0DB',
            ORANGE: '#FA967E',
            YELLOW: '#F6F2D4',
            HOVER_ORANGE: '#FFC18E',
            Card_2: '#94A5E2',
            Card_3: '#E29B2F',
            Card_4: '#EDFFF1',
            Notification_red: '#FF7D7D',
            Light_blue: '#ECF6FF',
            Blue_Gradient: ['#8FC9FB', '#587AB4'],
            green: '#2A91A8',
            Feed_Gradient: ['#22577e13', '#ffffff00'],
            cyanBlue: '#CAF2FF',
            purple_light: '#F9F9FF',
            cream: '#FFF5ED',
            tealGreen: '#0D9488',
            brightYellow: '#FFD12D',
            CorrectGreen: '#BDFFC8',
            dividerColor: '#F5F5F5',
            ProfileColor: '#FFFFFF',
            ResuleColor: '#F5F5F5',
            labText: '#2A91A8',
            whiteYellow: '#FFFFFF',
            hilight: '#EDFFF1',
        },
        dark: false,
    },
    darkcolors: {
        colors: {
            ...DarkTheme.colors,
            achivementBackground: '#27333A',
            P: '#DFDEDE',
            chatHeaderBack: '#27333A',
            chatBackground: '#0C141A',
            BorderColor: '#808080',
            accountlinkBack: '#353A3D',
            dropDownText: '#DFDEDE',
            dropDownBack: '#353A3D',
            dropDownSelectBack: '#707070',
            tabActive: '#FFC18E',
            tabInActive: '#6AA4D4',
            certificateHeaderBack: '#707070',
            certificateHeader: '#FFFDF0',
            certiSubHeaderBack: '#27333A',
            certiSubHeaderTitle: '#ECF6FF',
            assessPointBackground: '#707070',
            assessPointText: '#FFFDF0',
            cardBackground: '#353A3D',
            cardBackground2: '#707070',
            assessmentTitle: '#FFC18E',
            CircularProgressInactive: '#707070',
            bottomBorder: '#27333A',
            headertext: '#6AA4D4',
            headerBackground: '#353A3D',
            MasterBackground: '#353A3D',
            cardBorder: '#27333A',
            titleOrange: '#FFC18E',
            background: '#0C141A',
            white: '#27333A',
            black: '#FFFDF0',
            black2: '#DFDEDE',
            primary: '#6AA4D4',
            secondary: '#FA967E',
            error: '#FF6B6B',
            success: '#56D6C7',
            warning: '#FF7D7D',
            Blue_2: '#6AA4D4',
            Blue_Theme: '#6AA4D4',
            lightBlue3: '#95CDFE',
            Grey_3: '#DFDEDE',
            Grey_1: '#808080',
            Grey_2: '#27333A',
            Grey_4: '#DFDEDE',
            Card_Gradian: '#6AA4D4',
            ORANGE: '#FA967E',
            YELLOW: '#F6F2D4',
            HOVER_ORANGE: '#FFC18E',
            Card_2: '#94A5E2',
            Card_3: '#E29B2F',
            Card_4: '#707070',
            Notification_red: '#FF7D7D',
            Light_blue: '#27333A',
            Blue_Gradient: ['#5084A5', '#0C1419'],
            green: '#2A91A8',
            Feed_Gradient: ['#707070', '#0C1419'],
            cyanBlue: '#CAF2FF',
            purple_light: '#27333A',
            cream: '#FFF5ED',
            tealGreen: '#0D9488',
            brightYellow: '#FFD12D',
            CorrectGreen: '#BDFFC8',
            dividerColor: '#707070',
            ProfileColor: '#f5f5f5',
            ResuleColor: '#353A3D',
            labText: '#FFF5ED',
            whiteYellow: '#F6F2D4',
            hilight: '#58705d',
        },
        dark: true,
    },
    fontFamily: {
        NunitoBlack: 'Nunito-Black',
        NunitoBlackItalic: 'Nunito-BlackItalic',
        NunitoBold: 'Nunito-Bold',
        NunitoBoldItalic: 'Nunito-BoldItalic',
        NunitoExtraBold: 'Nunito-ExtraBold',
        NunitoExtraBoldItalic: 'Nunito-ExtraBoldItalic',
        NunitoItalic: 'Nunito-Italic',
        NunitoLight: 'Nunito-Light',
        NunitoLightItalic: 'Nunito-LightItalic',
        NunitoExtraLight: 'Nunito-ExtraLight',
        NunitoExtraLightItalic: 'Nunito-ExtraLightItalic',
        NunitoMedium: 'Nunito-Medium',
        NunitoMediumItalic: 'Nunito-MediumItalic',
        NunitoRegular: 'Nunito-Regular',
        NunitoSemiBold: 'Nunito-SemiBold',
        NunitoSemiBoldItalic: 'Nunito-SemiBoldItalic',
        RalewayBlack: 'Raleway-Black',
        RalewayBlackItalic: 'Raleway-BlackItalic',
        RalewayBold: 'Raleway-Bold',
        RalewayBoldItalic: 'Raleway-BoldItalic',
        RalewayExtraBold: 'Raleway-ExtraBold',
        RalewayExtraBoldItalic: 'Raleway-ExtraBoldItalic',
        RalewayExtraLight: 'Raleway-ExtraLight',
        RalewayExtraLightItalic: 'Raleway-ExtraLightItalic',
        RalewayLight: 'Raleway-Light',
        RalewayLightItalic: 'Raleway-LightItalic',
        RalewayMedium: 'Raleway-Medium',
        RalewayMediumItalic: 'Raleway-MediumItalic',
        RalewayRegular: 'Raleway-Regular',
        RalewaySemiBold: 'Raleway-SemiBold',
        RalewaySemiBoldItalic: 'Raleway-SemiBoldItalic',
        RalewayThin: 'Raleway-Thin',
        RalewayThinItalic: 'Raleway-ThinItalic',

    },
    themes: {
        cardPurple: {
            padding: RFValue(20),
            borderRadius: RFValue(5),
        },
        iosShadow:{
            shadowOffset: { width: 0, height: 1.5 },
            shadowOpacity: 0.5,
            shadowRadius:1.5,
          },
    },
};

