export const ModuleNavigation = [
    {
        icon: "Ass",
        cardTitle: "CARD_ASSESSEMENT_CURRENT_ASSESSMENTS",
        link: "CurrentAssessments",
        activityType: "module_current_assessments",
    },
    {
        icon: "PastAss",
        cardTitle: "CARD_ASSESSEMENT_PAST_ASSESSMENTS",
        link: "PastAssessments",
        activityType: "module_past_assessments",
    },
    {
        icon: "checking-tool.svg",
        cardTitle: "TITLE_SCREENING",
        link: "Screening",
        type: 'Screening',
        activityType: "module_screening_tool",
    },
    {
        icon: "learning.svg",
        cardTitle: "TITLE_CASE_DEFINITION",
        link: "AlgorithmList",
        type: 'Case Definition',
        activityType: "module_case_defintion",
    },
    {
        icon: "algorithm.svg",
        cardTitle: "TITLE_DIAGNOSIS_ALGORITHM",
        link: "AlgorithmList",
        type: 'Diagnosis Algorithm',
        activityType: "module_diagnostic_care_cascade",
    },
    {
        icon: "adr.svg",
        cardTitle: "TITLE_GUIDANCE_ON_ADR",
        link: "AlgorithmList",
        type: 'Guidance on ADR',
        activityType: "module_guidance_on_adr",
    },
    {
        icon: "treatment.svg",
        cardTitle: "TITLE_TREATMENT_ALGORITHM",
        link: "AlgorithmList",
        type: 'Treatment Algorithm',
        activityType: "module_treatment_care_cascade",
    },
    {
        icon: "latent-tb.svg",
        cardTitle: "TITLE_LATENT_TB_INFECTION",
        link: "AlgorithmList",
        type: 'Latent TB Infection',
        activityType: "module_latent_tb",
    },
    {
        icon: "algorithm.svg",
        cardTitle: "TITLE_DIFFERENTIANTED_CARE",
        link: "AlgorithmList",
        type: 'Differentiated Care Of TB Patients',
        activityType: "module_differentiated_care_tb_patient",
    },
    // {
    //     backEnd: "TITLE_CGC_INTERVENTION",
    //     tab: 'CGCIntervention',
    //     screen: 'CGCIntervention',
    //     type: 'CGC',
    //     svg: 'Intervention',
    //     image: "../intervention.svg",
    //     reference: "3",
    //     link: "AlgorithmList",
    //     sectionTitle: "TITLE_CGC_INTERVENTION"
    // },
    {
        icon: "hospital",
        cardTitle: "TITLE_NEAR_HEALTH_FACILITY",
        link: "ReferralHealthFacility",
        activityType: "module_Referral-Health Facility",
    },
    // {
    //     backEnd: "TITLE_RESOURCE_MATERIALS",
    //     tab: 'MaterialsIndex',
    //     screen: 'ResourceMaterials',
    //     svg: 'BookOpen',
    //     image: "../resource-materials.svg",
    //     reference: "5",
    //     link: "ResourceMaterials",
    //     sectionTitle: "TITLE_RESOURCE_MATERIALS"
    // },
]